export const SPIN_ANIMATION = {
  FRAME_TIME: 1000 / 60,
  SPEED: 16,
  DURATION: 2000,
  COLUMN_DELAYS: [0, 300, 600],
  SYMBOLS_ABOVE: 2,
  SYMBOLS_BELOW: 2,
  MIN_STOP_DISTANCE: 1,
};

export const WIN_PULSE_ANIMATION = {
  DURATION: 1000,
  BASE_SCALE: 1.0,
  PULSE_AMPLITUDE: 0.3,
  PULSE_COUNT: 4,
};

export const MASK_CONFIG = {
  WIDTH: 1000,
  HEIGHT: 515,
  OFFSET_Y: -10,
  MASK_COLOR: 0xffffff,
  DEBUG_COLOR: 0xff0000,
  DEBUG: false,
  DEBUG_ALPHA: 0.3,
};

export const SYMBOL_CONFIG = {
  GRID_SIZE: 80,
  GRID_GAP: 90,
  COUNT: 5,
  ROWS: 3,
  COLUMNS: 3,
  DEFAULT_ROW_HEIGHT: 140,
};

export const UI_CONFIG = {
  BOARD_SCALE: 0.7,
  SYMBOL_WIDTH: 130,
  SYMBOL_HEIGHT: 125,
  SYMBOLS_OFFSET_Y: -10,
  
  PLAY_BUTTON_SCALE: 0.65,
  PLAY_BUTTON_OFFSET_X: 200,
  PLAY_BUTTON_OFFSET_Y: 110,
  BUTTON_PRESSED_SCALE: 0.95,
  
  WIN_INFO_SCALE_Y: 0.55,
  WIN_INFO_OFFSET_X: -70,
  WIN_INFO_OFFSET_Y: 110,
  
  RESULT_TEXT_FONT_SIZE: 24,
  RESULT_TEXT_SHADOW_BLUR: 4,
  RESULT_TEXT_SHADOW_DISTANCE: 2,
  RESULT_TEXT_SHADOW_ANGLE: Math.PI / 6,
};

